### ISSUE TITLE
Config.toml not being picked up?

### ISSUE THREAD

**Issue by nikitavoloboev** [calintat/minimal#11]
I [deployed my site](http://www.nikitavoloboev.xyz/) with your theme and it is really awesome. Thank you for it. 💛

One thing though, on production, for some reason, config.toml doesn't seem to pick up what I specified. 

For example, here is how site looks on localhost : 

![2017-08-04 at 03 25](https://user-images.githubusercontent.com/6391776/28950490-90a2f100-78c4-11e7-96b5-c8c5c8586dbf.png)

And here is the live website : 

http://www.nikitavoloboev.xyz/

Not really sure why that happens.

**Comment by nikitavoloboev** [comment]
Also is there a reason why 'About' links to my GitHub page by default on this page : https://nikitavoloboev.xyz/about/.

I never specified this link anywhere I believe.

**Comment by nikitavoloboev** [comment]
I tried to hardcode the changes to the index.html like so : 


![2017-08-04 at 04 03](https://user-images.githubusercontent.com/6391776/28951235-f6ccaf66-78c9-11e7-8d43-724dc811966e.png)


but not sure how to use the changes since I can't push to minimal as I don't have permission and I don't think it picks it up like that.

**Comment by calintat** [comment]
Hi @nikitavoloboev,
If you want to make local changes to the theme, I suggest you clone the repository instead of adding it as a submodule. But if you think any of those changes could be useful to other people then feel free to make a pull request. For your changes in particular, I added support for customisable footer messages (just add `copyright` to `[params]` in your config) and support for hyperlinks in the description and footer message (just use markdown syntax, i.e. `[Hugo](https://gohugo.io)` so you can keep using the theme as a submodule (you'll just have to update it first as explained in the readme). Regarding your question about the link for "About", I pushed an update a few days ago that should fix that. Basically the theme thinks your page represents a project (because you have specified a description) but with the latest update, the link will just be the url of the content unless you specify a GitHub link or website.

**Comment by nikitavoloboev** [comment]
This works really well. Thank you.

One more question, is it possible to get rid of the link in About all together?

**Comment by nikitavoloboev** [comment]
Really strangely, locally I get my website to render well and have the description show and yet on production no description is shown at all.

I used your advice and use minimal as simple clone and not submodule. 

Would really love any advice on why that might happen. [Here](https://github.com/nikitavoloboev/nikitavoloboev.github.io) is the repository of the website.

Thank you for any help.

**Comment by nikitavoloboev** [comment]
I really don't get why Description parameter does not get picked up on deploy when it works perfectly fine locally.

**Comment by calintat** [comment]
Hi, first of all note that the description is actually present in [public/index.html](https://github.com/nikitavoloboev/nikitavoloboev.github.io/blob/master/public/index.html#L133) so the production website is rendered properly by Hugo. The problem is that GitHub Pages didn't rebuild your site. If you read the documentation for GitHub Pages, it says [here](https://help.github.com/articles/user-organization-and-project-pages) that the source files for a user page must be in the `master` branch of your `username.github.io` repo (not in a subdirectory as it's the case with your site).

I suggest you make sure the contents of your `public` directory are at the root of your repository. 
The Hugo docs explain how to achieve this a an elegant way [here](https://gohugo.io/hosting-and-deployment/hosting-on-github/#host-github-user-or-organization-pages). This is how I do it for my site.

The link in About comes from the [list item partial](https://github.com/calintat/minimal/blob/master/layouts/partials/list-item.html) which is used for both list items in list pages such as Posts and Projects on the example site but also for the header of single pages such as individual posts.
I'll try to remove the link for single pages in a future update but feel free to make a PR in the meantime.

**Comment by nikitavoloboev** [comment]
Hey @calintat 

I am actually using Netlify over GitHub pages. I [read through this](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/). And since my public folder contains the correct HTML, I have no idea why then the live version does not have that.

I even specify to pick changes from public folder 

![2017-08-06 at 22 25](https://user-images.githubusercontent.com/6391776/29006741-2a711004-7af6-11e7-9028-ffa8748a765c.png)

The strange thing is that it picks every other change, but not me changing the description.

**Comment by calintat** [comment]
Hi, it says Netlify does not support Hugo themes added as clones.
Try switching back to a submodule and deploy again.

Also what version of Hugo are you using on Netlify?

**Comment by nikitavoloboev** [comment]
I am running the latest hugo version I think as I did not specify the version.

Added the theme back as submodule, [still doesn't seem to fix it](https://www.nikitavoloboev.xyz/).

**Comment by nikitavoloboev** [comment]
Turns out, Netlify was using old version of Hugo. After specifying the version in settings, it works. 🎊
