### ISSUE TITLE
Add Patreon logo support

### ISSUE THREAD

**Issue by nikitavoloboev** [calintat/minimal#13]
It would be awesome to add Patreon logo so users can specify a Patreon website to show up in their upper bar.

I would add it myself but not sure what I should change for that. 

Thank you.

**Comment by calintat** [comment]
Hi, the icons on the navigation bar are taken from [Font Awesome](http://fontawesome.io). Unfortunately they don't have an icon for Patreon (yet). There is an [issue](https://github.com/FortAwesome/Font-Awesome/issues/3257) on their repo requesting a Patreon icon but it's over 3 years old so who knows when or if they'll ever release a Patreon icon. I have tried looking for other icon fonts but none of them seem to have icons for Patreon. If you want to add the logo manually, you would have to change [this line](https://github.com/calintat/minimal/blob/fa1838bc2214235040d1a48c83433d18b7a7c2de/layouts/partials/header.html#L47) in the header partial layout. For now I am closing this issue because adding support for images in the navigation bar doesn't really fit in the spirit of the theme (minimality and ease of use).

**Comment by nikitavoloboev** [comment]
Hey @calintat 

Can you help with one thing? I was trying to add two custom icons however I am confused about one thing. What should I put in the i class section?

So I was thinking of adding a telegram icon which I [found online](https://image.flaticon.com/icons/png/512/152/152827.png). However one thing I am not sure of is how do I actually add this image so it shows inline nicely. I got something like this : 

```HTML
<li class="navbar-icon"><a href="https://t.me/nikivi"><i class=""></i></li>
```

Right above the <li> tag : 

![2017-08-31 at 03 15](https://user-images.githubusercontent.com/6391776/29901852-bebfb758-8dfa-11e7-9a97-37e1f5a490ee.png)

Not really sure how to make it work.

Thank you for a lot for any help.

**Comment by nikitavoloboev** [comment]
Never mind, there actually is a Font Awesome telegram icon already and it works well. 

However I can't quite figure out how to add custom Patreon logo there, I still get the issue of bad formatting. The whole layout messes up when I try to add it. 😞
