### ISSUE TITLE
support for Bitbucket/Gitlab repos

### ISSUE THREAD

**Issue by tjaartvdwalt** [calintat/minimal#16]
It would be really cool if there could be project support for online code hosting services other than Github. Here is my suggestion:

- We add `bitbucketUsername` and `gitlabUsername` to the main config.
- In the project frontmatter we support `repoGithub` `repoBitbucket`, `repoGitlab`. 
- `repo` remain unchanged, (points to Github) to support existing code.

I am willing to create a PR if this seems reasonable.

**Comment by tjaartvdwalt** [comment]
Thinking about it some more, we could also simply add a `url` to the project frontmatter.

**Comment by calintat** [comment]
Hi, I like your idea but I have another suggestion. How about adding a field `host` or `repoHost` to the front matter for changing the hosting service of a project? If the field is not set, it should default to GitHub so that existing code still works (its value should be one of `github`, `bitbucket` or `gitlab`).

**Comment by calintat** [comment]
Hi @tjaartvdwalt, I added support for custom redirect links (just use the field `link` in the front matter). I also added support for GitLab and Bitbucket repositories. You first have to add `gitlabUsername` and/or `bitbucketUsername` to your site config, and then you can change the hosting service from the default (i.e. Github) to either GitLab or Bitbucket by using the `repoHost` field in the project front matter.
